### ISSUE TITLE
No "dependencies" method in sbt plugin version 1.0.7

### ISSUE THREAD

**Issue by marcinmicek** [heremaps/here-sbt-bom#23]
In [this section](https://github.com/heremaps/here-sbt-bom?tab=readme-ov-file#load-the-plugin) there is a line:
`addSbtPlugin("com.here.platform" % "sbt-bom" % "1.0.7")`

If we use plugin version 1.0.7 then we cannot use method `dependencies` mentioned in [this section](https://github.com/heremaps/here-sbt-bom?tab=readme-ov-file#use-it-in-dependencyoverrides--bomdependencies) in line:
`lazy val jacksonDependencies = Bom.dependencies("com.fasterxml.jackson" % "jackson-bom" % "2.14.2")`
due to the fact that it doesn't exist in this version. To fix it we need to upgrade plugin to version 1.0.14, so we should do the following change:
`addSbtPlugin("com.here.platform" % "sbt-bom" % "1.0.7")` into `addSbtPlugin("com.here.platform" % "sbt-bom" % "1.0.14")`

**Comment by molekyla** [comment]
@marcinmicek Good catch. Indeed readme file is out of sync with the latest version. You should use the latest version: 1.0.14
